### PR TITLE
Make CSS dependencies work on Firefox OS devices.

### LINKED ISSUE #144: On Firefox OS devices, the CSS stylesheets do not work in jQuery mode
It works on desktop browsers.
It also works in ServiceWorker mode, both on mobile and desktop

### PR DESCRIPTION
**Pull request by mossroy**
Fixes #144

### CODE REVIEW

File: www/js/app.js [hunk 1]
```diff
@@ -1001,8 +1001,21 @@ define(['jquery', 'abstractBackend', 'util', 'cookies','geometry','osabstraction
...
+                            var mediaAttribute = '';
+                            if (mediaAttributeValue) {
+                                mediaAttribute = ' media="' + mediaAttributeValue + '"';
+                            }
+                            var disabledAttributeValue = link.attr('media');
+                            var disabledAttribute = '';
+                            if (disabledAttributeValue) {
+                                disabledAttribute = ' disabled="' + disabledAttributeValue + '"';
+                            }
+                            link.replaceWith('<style type="text/css"' + mediaAttribute + disabledAttribute + '>' + cssContent + '</style>');
```
Comment (peter-x) [inline www/js/app.js]: The content should probably be escaped here, perhaps in this way: http://jonraasch.com/blog/javascript-style-node

**Comment by mossroy** [comment]
I escape the CSS per your comment. Does it look fine?

**Comment by peter-x** [comment]
Looks good!
